// <auto-generated />

using System.Linq;
using Godot;

namespace Widgets;

public partial class TextWidget
{
    private void DrawSelection()
    {
        var selStart = SelectionStart();
        var selEnd = SelectionEnd();
        var (startLine, startCol) = LocateCaret(selStart);
        var (endLine, endCol) = LocateCaret(selEnd);

        var font = GetFont(THEME_FONT_DEFAULT);
        var fontSize = _resolvedFontSize > 0 ? _resolvedFontSize : ResolveFontSize();
        var lineHeight = font.GetHeight(fontSize);
        var ascent = font.GetAscent(fontSize);
        var selColor = SelectionColor with { A = 0.5f };

        for (var i = startLine; i <= endLine && i < _lineRids.Count; i++)
        {
            var originX = GetLineDrawOriginX(i);
            var baselineY = GetLineBaselineY(i);
            var topY = baselineY - ascent;

            var leftCol = i == startLine ? startCol : 0;
            var rightCol = i == endLine ? endCol : GetLineShapedLength(i);

            var leftX = originX + GetCaretRelativeXOnLine(i, leftCol);
            var rightX = originX + GetCaretRelativeXOnLine(i, rightCol);
            var content = GetContentRect();
            leftX = Mathf.Max(leftX, content.Position.X);
            rightX = Mathf.Min(rightX, content.Position.X + content.Size.X);
            if (rightX <= leftX) continue;

            DrawRect(new Rect2(leftX, topY, rightX - leftX, lineHeight), selColor);
        }
    }

    private void DrawCaret()
    {
        var font = GetFont(THEME_FONT_DEFAULT);
        var fontSize = _resolvedFontSize > 0 ? _resolvedFontSize : ResolveFontSize();
        var ascent = font.GetAscent(fontSize);
        var lineHeight = font.GetHeight(fontSize);

        var (line, col) = LocateCaret(CaretIndex);
        if (line >= _lineRids.Count) return;

        var caretX = GetLineDrawOriginX(line) + GetCaretRelativeXOnLine(line, col);
        var caretTopY = GetLineBaselineY(line) - ascent;

        DrawRect(new Rect2(caretX, caretTopY, CaretWidth, lineHeight), CaretColor);
    }
    
    private void DrawTextMarks()
    {
        EnsureTextMarks();
        if (_cachedTextMarks == null || _cachedTextMarks.Count == 0) return;
        foreach (var mark in _cachedTextMarks.Where(mark => !IsMarkSuppressed(mark))) { DrawTextMark(mark); }
    }

    private void DrawTextMark(TextMark mark)
    {
        var start = Mathf.Clamp(mark.Start, 0, _text.Length);
        var end = Mathf.Clamp(mark.End, start, _text.Length);
        if (start >= end) return;

        var (startLine, startCol) = LocateCaret(start);
        var (endLine, endCol) = LocateCaret(end);

        var font = GetFont(THEME_FONT_DEFAULT);
        var fontSize = _resolvedFontSize > 0 ? _resolvedFontSize : ResolveFontSize();
        var descent = font.GetDescent(fontSize);

        var content = GetContentRect();
        var contentLeft = content.Position.X;
        var contentRight = content.Position.X + content.Size.X;

        for (var line = startLine; line <= endLine && line < _lineRids.Count; line++)
        {
            var rid = _lineRids[line];
            if (!rid.IsValid) continue;

            var originX = GetLineDrawOriginX(line);
            var baselineY = GetLineBaselineY(line);
            var squiggleY = baselineY + descent * 0.5f;

            var leftCol = line == startLine ? startCol : 0;
            var rightCol = line == endLine ? endCol : GetLineShapedLength(line);

            var leftX = originX + GetCaretRelativeXOnLine(line, leftCol);
            var rightX = originX + GetCaretRelativeXOnLine(line, rightCol);

            leftX = Mathf.Max(leftX, contentLeft);
            rightX = Mathf.Min(rightX, contentRight);
            if (rightX <= leftX) continue;

            DrawWavyLine(leftX, rightX, squiggleY, mark.Color);
        }
    }

    private void DrawWavyLine(float x1, float x2, float y, Color color)
    {
        const float PERIOD = 4f;
        const float AMPLITUDE = 1.5f;

        var width = x2 - x1;
        if (width <= 0) return;

        var sampleCount = Mathf.Max(2, Mathf.CeilToInt(width));
        var points = new Vector2[sampleCount];
        for (var k = 0; k < sampleCount; k++)
        {
            var t = (float)k / (sampleCount - 1);
            var x = x1 + t * width;
            var phase = (x - x1) / PERIOD * Mathf.Tau;
            var py = y + AMPLITUDE * Mathf.Sin(phase);
            points[k] = new Vector2(x, py);
        }
        DrawPolyline(points, color);
    }

    private void DrawScrollbar()
    {
        var max = GetMaxScrollOffsetY();
        if (max <= 0f) return;

        var content = GetContentRect();
        var trackX = content.Position.X + content.Size.X - SCROLLBAR_WIDTH;
        var trackY = content.Position.Y;
        var trackHeight = content.Size.Y;

        var font = GetFont(THEME_FONT_DEFAULT);
        var fontSize = _resolvedFontSize > 0 ? _resolvedFontSize : ResolveFontSize();
        var lineHeight = font.GetHeight(fontSize);
        var advance = lineHeight + _lineSpacing;
        var viewportHeight = _maxLines * advance;
        var totalContentHeight = _lineRids.Count * advance;

        var thumbHeight = Mathf.Max(SCROLLBAR_MIN_THUMB_HEIGHT, trackHeight * (viewportHeight / totalContentHeight));
        var thumbY = trackY + (_scrollOffsetY / max) * (trackHeight - thumbHeight);

        var caretColor = CaretColor;
        DrawRect(new Rect2(trackX, trackY, SCROLLBAR_WIDTH, trackHeight), caretColor with { A = 0.15f });
        DrawRect(new Rect2(trackX, thumbY, SCROLLBAR_WIDTH, thumbHeight), caretColor with { A = 0.5f });
    }
 
    private void DrawBackground()
    {
        var rect = new Rect2(Vector2.Zero, Size);
        CurrentBaseStyle().Draw(GetCanvasItem(), rect);
        if (HasFocus() && _editable) GetStyle(THEME_STYLE_FOCUS).Draw(GetCanvasItem(), rect);
    }
 
    private bool ShouldDrawSelection() => !string.IsNullOrEmpty(_text) && HasSelection && HasFocus();
    private bool ShouldDrawCaret() => HasFocus() && _editable && _caretVisible;
 
    private void DrawText()
    {
        var color = ResolveTextColor();
        var (clipL, clipR) = ResolveHorizontalClip();
        var outlineSize = string.IsNullOrEmpty(_text) ? 0 : OutlineSize;
        var outlineColor = outlineSize > 0 ? FontOutlineColor : default;

        for (var i = 0; i < _lineRids.Count; i++)
        {
            var rid = _lineRids[i];
            if (!rid.IsValid) continue;
            var origin = new Vector2(GetLineDrawOriginX(i), GetLineBaselineY(i));
            if (outlineSize > 0) Ts.ShapedTextDrawOutline(rid, GetCanvasItem(), origin, clipL, clipR, outlineSize, outlineColor);
            Ts.ShapedTextDraw(rid, GetCanvasItem(), origin, clipL, clipR, color);
        }
    }
    
    private void DrawSelectedText()
    {
        if (!_fontSelectedColorEnabled) return;
        if (!HasSelection || !HasFocus()) return;

        var selStart = SelectionStart();
        var selEnd = SelectionEnd();
        var (startLine, startCol) = LocateCaret(selStart);
        var (endLine, endCol) = LocateCaret(selEnd);

        var color = FontSelectedColor;
        var outlineSize = OutlineSize;
        var outlineColor = outlineSize > 0 ? FontOutlineColor : default;

        for (var i = startLine; i <= endLine && i < _lineRids.Count; i++)
        {
            var rid = _lineRids[i];
            if (!rid.IsValid) continue;

            var originX = GetLineDrawOriginX(i);
            var origin = new Vector2(originX, GetLineBaselineY(i));

            var leftCol = i == startLine ? startCol : 0;
            var rightCol = i == endLine ? endCol : GetLineShapedLength(i);

            var leftX = originX + GetCaretRelativeXOnLine(i, leftCol);
            var rightX = originX + GetCaretRelativeXOnLine(i, rightCol);
            if (rightX <= leftX) continue;

            if (outlineSize > 0) Ts.ShapedTextDrawOutline(rid, GetCanvasItem(), origin, leftX, rightX, outlineSize, outlineColor);
            Ts.ShapedTextDraw(rid, GetCanvasItem(), origin, leftX, rightX, color);
        }
    }
 
    private void DrawOverflowMarker()
    {
        if (!_showMarker || !_markerRid.IsValid) return;
        var origin = new Vector2(
            GetLineDrawOriginX(_markerLineIndex) + _markerLineX,
            GetLineBaselineY(_markerLineIndex));
        Ts.ShapedTextDraw(_markerRid, GetCanvasItem(), origin, -1f, -1f, ResolveTextColor());
    }
 
    private Color ResolveTextColor()
    {
        if (string.IsNullOrEmpty(_text)) return PlaceholderColor;
        return !_editable ? ReadOnlyColor : FontColor;
    }
 
    private (float clipL, float clipR) ResolveHorizontalClip()
    {
        if (IsMultilineActive || GetMaxScrollOffsetX() <= 0f) return (-1f, -1f);
        return (_scrollOffsetX, _scrollOffsetX + GetContentRect().Size.X);
    }
}